name: Laravel
networks:
    app-network:
        driver: bridge
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopdienmay
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network